version: '2.4'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:11.9.6-ce.0'
    container_name: 'gitlab'
    mem_limit: '3GB'
    restart: 'always'
    hostname: "${SERVER_IP}"
    ports:
      - '80:80'
      - '443:443'
      - '23:22'
    networks:
      - tools
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
  jenkins:
    image: 'jenkinsci/blueocean:1.14.0'
    container_name: 'jenkins'
    mem_limit: '3GB'
    restart: 'always'
    hostname: "${SERVER_IP}"
    ports:
      - '8080:8080'
      - '50000:50000'
    networks:
      - tools
    volumes:
      - 'jenkins_home:/var/jenkins_home'
networks:
  tools:
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  jenkins_home:

